server:
  port: 13002
spring:
  application:
    name: cloud-manager
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-manager?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone:
        http://localhost:12001/eureka/
