server:
  port: 12002
spring:
  application:
    name: cloud-zuul
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone:
        http://localhost:12001/eureka/
zuul:
  routes: 
    cloud-ims: /item-service/**
    cloud-manager: /oss-service/**